version: '3'
name: "aandahl-dev-stack"
services:
  postgres:
    image: postgres
    container_name: "aandahl-db"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: aandahl
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
    container_name: "aandahl-cache"
    ports:
      - '6379:6379'
  serverless-redis-http:
    ports:
      - '8080:80'
    image: hiett/serverless-redis-http:latest
    container_name: "aandahl-srh"
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: 'redis://redis:6379' # Using `redis` hostname since they're in the same Docker network.